### PR TITLE
Update dependencies, fixes build on 24.04

### PR DESCRIPTION
**Pull request by jackpot51**
This may require testing installs.

### CODE REVIEW

**Review by mmstick — DISMISSED** [review]

**Comment by leviport** [comment]
I believe I'm seeing a regression with Refresh OS. When booting from Recovery, without adding this branch, the installer shows me a Refresh OS option at the first screen after language and keyboard layout selections. After adding this branch, the Refresh OS option is no longer there, and the next screen after keyboard/language selections is the "Clean Install" vs "Custom (Advanced)" screen.

I captured terminal output from running `sudo io.elementary.installer` with this branch added:

```
** (io.elementary.installer:5550): WARNING **: 18:52:26.951: Inhibitor.vala:42: Could not start screensaver interface: Failed to execute child process “dbus-launch” (No such file or directory)
could not get mode from distinst-v2: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable

** (io.elementary.installer:5550): WARNING **: 18:52:26.953: MainWindow.vala:309: failed to search for OS boot entries: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable

(io.elementary.installer:5550): GLib-GObject-CRITICAL **: 18:52:26.953: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

(io.elementary.installer:5550): GLib-CRITICAL **: 18:52:27.872: g_utf8_collate: assertion 'str2 != NULL' failed

(io.elementary.installer:5550): GLib-CRITICAL **: 18:52:27.872: g_utf8_collate: assertion 'str2 != NULL' failed

(io.elementary.installer:5550): GLib-CRITICAL **: 18:52:27.872: g_utf8_collate: assertion 'str2 != NULL' failed

(io.elementary.installer:5550): GLib-CRITICAL **: 18:52:27.872: g_utf8_collate: assertion 'str2 != NULL' failed

** (io.elementary.installer:5550): CRITICAL **: 18:52:30.257: installer_language_view_timeout: assertion 'self != NULL' failed

(io.elementary.installer:5550): GLib-GObject-CRITICAL **: 18:52:30.258: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
[INFO distinst:crates/disks/src/config/disks.rs:596] probed "/dev/sda"
[INFO distinst:crates/disks/src/config/disk.rs:164] obtaining disk information from /dev/sda
[INFO distinst:crates/disks/src/serial.rs:14] obtaining serial model from /dev/sda
[INFO distinst:crates/disk-ops/src/parted.rs:31] opening disk at /dev/sda
[INFO distinst:crates/disks/src/config/partitions/mod.rs:119] obtaining partition information from /dev/sda1
[INFO distinst:crates/disks/src/config/disks.rs:596] probed "/dev/nvme0n1"
[INFO distinst:crates/disks/src/config/disk.rs:164] obtaining disk information from /dev/nvme0n1
[INFO distinst:crates/disks/src/serial.rs:14] obtaining serial model from /dev/nvme0n1
[INFO distinst:crates/disk-ops/src/parted.rs:31] opening disk at /dev/nvme0n1
[INFO distinst:crates/disks/src/config/partitions/mod.rs:119] obtaining partition information from /dev/nvme0n1p1
[INFO distinst:crates/disks/src/config/partitions/mod.rs:119] obtaining partition information from /dev/nvme0n1p2
[INFO distinst:crates/disks/src/config/partitions/mod.rs:119] obtaining partition information from /dev/nvme0n1p3
[INFO distinst:crates/disks/src/config/partitions/mod.rs:119] obtaining partition information from /dev/nvme0n1p4
[INFO distinst:crates/disks/src/config/disks.rs:596] probed "/dev/zram0"
[INFO distinst:crates/external/src/lvm.rs:209] obtaining list of physical volumes
[DEBUG distinst:crates/disk-types/src/sector.rs:17] get block size for "/sys/class/block/sda"
[DEBUG distinst:crates/disk-types/src/sector.rs:17] get block size for "/sys/class/block/nvme0n1"
[INFO distinst:crates/disks/src/config/disk_trait.rs:60] child_dev "/dev/sda1" has mount_opt Some(MountInfo { source: "/dev/sda1", dest: "/media/recovery/adatatata", fstype: "vfat", options: ["rw", "nosuid", "nodev", "relatime", "uid=999", "gid=999", "fmask=0022", "dmask=0022", "codepage=437", "iocharset=iso8859-1", "shortname=mixed", "showexec", "utf8", "flush", "errors=remount-ro"], dump: 0, pass: 0 })
device: "/dev/sda"
[DEBUG distinst:crates/disk-types/src/sector.rs:17] get block size for "/sys/class/block/sda1"
[INFO distinst:crates/os-detect/src/lib.rs:52] detecting OS from device: "/dev/sda1"
[INFO distinst:crates/os-detect/src/lib.rs:68] detecting OS from "/tmp/distinst.3JjO3FCyOitI"
[INFO distinst:crates/os-detect/src/lib.rs:71] Found "/tmp/distinst.3JjO3FCyOitI/savedstuff"
[INFO distinst:crates/os-detect/src/lib.rs:71] Found "/tmp/distinst.3JjO3FCyOitI/trubble"
[INFO distinst:crates/os-detect/src/lib.rs:71] Found "/tmp/distinst.3JjO3FCyOitI/FSCK0000.REC"
[INFO distinst:crates/os-detect/src/lib.rs:71] Found "/tmp/distinst.3JjO3FCyOitI/.Trash-1000"
[INFO distinst:crates/os-detect/src/lib.rs:71] Found "/tmp/distinst.3JjO3FCyOitI/work-scripts"
[INFO distinst:crates/os-detect/src/lib.rs:71] Found "/tmp/distinst.3JjO3FCyOitI/keyboard-layouts"
[INFO distinst:crates/os-detect/src/lib.rs:71] Found "/tmp/distinst.3JjO3FCyOitI/buildchain-nmcli.txt"
[INFO distinst:crates/os-detect/src/lib.rs:71] Found "/tmp/distinst.3JjO3FCyOitI/buildchain-lspci-k.txt"
[INFO distinst:crates/os-detect/src/lib.rs:71] Found "/tmp/distinst.3JjO3FCyOitI/distinstv2-deps-refresh-log.txt"
[INFO distinst:crates/os-detect/src/lib.rs:71] Found "/tmp/distinst.3JjO3FCyOitI/.Trash-999"
[INFO distinst:src/auto/options/mod.rs:176] found erase option on "/dev/sda": 30515200 sectors
device: "/dev/nvme0n1"
[DEBUG distinst:crates/disk-types/src/sector.rs:17] get block size for "/sys/class/block/nvme0n1p1"
[INFO distinst:crates/os-detect/src/lib.rs:52] detecting OS from device: "/dev/nvme0n1p1"
[INFO distinst:crates/os-detect/src/lib.rs:68] detecting OS from "/tmp/distinst.zm9BgwZ7xbqz"
[INFO distinst:crates/os-detect/src/lib.rs:71] Found "/tmp/distinst.zm9BgwZ7xbqz/EFI"
[INFO distinst:crates/os-detect/src/lib.rs:71] Found "/tmp/distinst.zm9BgwZ7xbqz/loader"
[INFO distinst:crates/os-detect/src/lib.rs:71] Found "/tmp/distinst.zm9BgwZ7xbqz/e6216f9de7d2aad16b9f560265c27a01"
[DEBUG distinst:crates/disk-types/src/sector.rs:17] get block size for "/sys/class/block/nvme0n1p2"
[INFO distinst:crates/os-detect/src/lib.rs:52] detecting OS from device: "/dev/nvme0n1p2"
[DEBUG distinst:crates/disk-types/src/sector.rs:17] get block size for "/sys/class/block/nvme0n1p3"
[DEBUG distinst:crates/disk-types/src/sector.rs:17] get block size for "/sys/class/block/nvme0n1p4"
[INFO distinst:src/auto/options/mod.rs:176] found erase option on "/dev/nvme0n1": 1000215216 sectors

(process:5613): dconf-WARNING **: 18:52:33.193: failed to commit changes to dconf: Failed to execute child process “dbus-launch” (No such file or directory)

(process:5620): dconf-WARNING **: 18:52:34.350: failed to commit changes to dconf: Failed to execute child process “dbus-launch” (No such file or directory)

(process:5627): dconf-WARNING **: 18:52:34.391: failed to commit changes to dconf: Failed to execute child process “dbus-launch” (No such file or directory)
```

**Comment by XV-02** [comment]
I also saw the same issue as Levi when attempting an install with this PR, which I do not see with the currently released version of distinst-v2. No refresh option is present.

**Comment by jackpot51** [comment]
I reduced the upgraded dependencies, please try again.

**Review by leviport — CHANGES_REQUESTED** [review]
No change from previous behavior, the refresh option is never presented.

The terminal output looks pretty much identical as well: [distinstv2-deps-refresh-log-2.txt](https://github.com/pop-os/distinst-v2/files/14199674/distinstv2-deps-refresh-log-2.txt)

**Comment by jackpot51** [comment]
@mmstick do you have any thoughts on this?

**Comment by mmstick** [comment]
I will have to try it out. The logs for the DBus service won't be shown in the distinst logs, but I don't think it's currently logging anything that's useful. Service name `com.system76.Distinst`.

**Comment by jackpot51** [comment]
@mmstick do you have any thoughts on this?

**Comment by mmstick** [comment]
This seems to be the issue

screenshot-2024-03-20-19-12-21

**Comment by mmstick** [comment]
Fixed by updating zbus from 2.0 to 3.0

**Comment by leviport** [comment]
The Refresh OS button has reappeared, but now I'm seeing a new problem. I'm seeing consistent failures when attempting encrypted installs. Here is an installer.log of the failure: [distinst-v2-installer.log](https://github.com/pop-os/distinst-v2/files/14728195/distinst-v2-installer.log)

Unencrypted installs seem to install fine though.

Refreshing an unencrypted install works as expected.

Refreshing an encrypted install doesn't seem to work, as it rejects the encryption password, even though I'm pretty sure I didn't typo it dozens of times consecutively. I'm guessing that's related to the error in the log above where the encrypted volume can't be mounted.

**Comment by mmstick** [comment]
@leviport I haven't been able to replicate in a VM. Was anything other than the distinst-v2 package updated? The log from the installer says that the error returned from running `cryptsetup open` is exit code 4, which means `wrong device specified`. Do you have logs from distinst-v2? `journalctl /usr/bin/com.system76.Distinst`.

**Comment by mmstick** [comment]
The only thing distinst-v2 is used for by the installer is to search for refresh OS options, so I don't think this is related.

**Comment by leviport** [comment]
I'll take another look today and gather distinst-v2 logs if it's still acting up on me. I had a lot of plates spinning that day, so it's possible that I goofed something up along the way.

**Comment by leviport** [comment]
Alright, I have new results. I was starting with ISO version 40 instead of 39, since 40 was released yesterday. Now, encrypted and non-encrypted installs, both from a live disk and from the recovery partition, are working as expected with this update.

With _only_ this update installed, refreshing encrypted and non-encrypted installs from live disk or recovery partition are all working fine.

If I install all available updates in the live environment, not just this update after adding the staging branch, all installs seem fine, but all refreshes break. Upgraded packages are `libudev1`, `system76-power`, and `udev`. A new package, `systemd-hwe-hwdb`, is also installed with an `apt-upgrade`. I have a hunch the `udev` stuff is to blame, but that's just a hunch.

Here are logs from such a refresh:
- installer.log: [oryp12-recovery-refresh-encrypted-failure-installer.log](https://github.com/pop-os/distinst-v2/files/14765165/oryp12-recovery-refresh-encrypted-failure-installer.log)
- distinst log: [oryp12-recovery-refresh-encrypted-failure-distinst.log](https://github.com/pop-os/distinst-v2/files/14765166/oryp12-recovery-refresh-encrypted-failure-distinst.log)

**Review by leviport — APPROVED** [review]
Since this update doesn't seem to be the problem, I'm approving this PR. There may be things to fix in the future, but I don't think this PR was the source of the issues I was seeing.

**Pull request merged**
